name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Wuerike/standard-version-release-branch@develop
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ github.event.inputs.version }}
          origin_branch: develop
          target_branch: main
          as_draft: true
          pr_template: |
            ## Motivo da mudança

            Preencha o motivo da mudança.
